/* SPDX-License-Identifier: GPL-3.0-only */
#ifndef RETVRN99_GSWSOUND_ABI_H
#define RETVRN99_GSWSOUND_ABI_H

#include "gswsound_types.h"

#define GSW_PCM_DEFAULT_CONTROL_BASE 0xF1001000UL
#define GSW_PCM_CONTROL_SIZE         0x00001000UL
#define GSW_PCM_INTERFACE_VERSION    1UL
#define GSW_PCM_RING_MIN_SIZE        4096UL
#define GSW_PCM_RING_MAX_SIZE        (256UL * 1024UL)
#define GSW_PCM_RING_GPA_ALIGNMENT   16UL

#define GSW_PCM_RATE_11025 11025UL
#define GSW_PCM_RATE_22050 22050UL
#define GSW_PCM_RATE_44100 44100UL
#define GSW_PCM_RATE_48000 48000UL

#define GSW_PCM_REG_ID              0x00UL
#define GSW_PCM_REG_VERSION         0x04UL
#define GSW_PCM_REG_CAPABILITIES    0x08UL
#define GSW_PCM_REG_STATUS          0x0CUL
#define GSW_PCM_REG_CONTROL         0x10UL
#define GSW_PCM_REG_SAMPLE_RATE     0x14UL
#define GSW_PCM_REG_FORMAT          0x18UL
#define GSW_PCM_REG_RING_GPA_LOW    0x1CUL
#define GSW_PCM_REG_RING_GPA_HIGH   0x20UL
#define GSW_PCM_REG_RING_SIZE       0x24UL
#define GSW_PCM_REG_RING_HEAD       0x28UL
#define GSW_PCM_REG_RING_TAIL       0x2CUL
#define GSW_PCM_REG_PERIOD_BYTES    0x30UL
#define GSW_PCM_REG_IRQ_ENABLE      0x34UL
#define GSW_PCM_REG_IRQ_STATUS      0x38UL
#define GSW_PCM_REG_POSITION_LOW    0x3CUL
#define GSW_PCM_REG_POSITION_HIGH   0x40UL
#define GSW_PCM_REG_XRUN_COUNT      0x44UL
#define GSW_PCM_REG_INVALID_COUNT   0x48UL
#define GSW_PCM_REG_AVAILABLE_BYTES 0x4CUL
#define GSW_PCM_REG_MASTER_GAIN     0x50UL

#define GSW_PCM_ID 0x31575347UL /* "GSW1" in little-endian register order. */

#define GSW_PCM_CAP_PLAYBACK   (1UL << 0)
#define GSW_PCM_CAP_PCM_U8     (1UL << 1)
#define GSW_PCM_CAP_PCM_S16    (1UL << 2)
#define GSW_PCM_CAP_MONO       (1UL << 3)
#define GSW_PCM_CAP_STEREO     (1UL << 4)
#define GSW_PCM_CAP_PERIOD_IRQ (1UL << 5)
#define GSW_PCM_CAP_MASTER_GAIN (1UL << 6)
#define GSW_PCM_CAPABILITIES ( \
    GSW_PCM_CAP_PLAYBACK | GSW_PCM_CAP_PCM_U8 | GSW_PCM_CAP_PCM_S16 | \
    GSW_PCM_CAP_MONO | GSW_PCM_CAP_STEREO | GSW_PCM_CAP_PERIOD_IRQ | \
    GSW_PCM_CAP_MASTER_GAIN)
#define GSW_PCM_REQUIRED_CAPS GSW_PCM_CAPABILITIES

#define GSW_PCM_STATUS_READY      (1UL << 0)
#define GSW_PCM_STATUS_RUNNING    (1UL << 1)
#define GSW_PCM_STATUS_BAD_CONFIG (1UL << 2)
#define GSW_PCM_STATUS_ERROR      GSW_PCM_STATUS_BAD_CONFIG
#define GSW_PCM_STATUS_UNDERRUN   (1UL << 3)

#define GSW_PCM_CONTROL_START (1UL << 0)
#define GSW_PCM_CONTROL_STOP  (1UL << 1)
#define GSW_PCM_CONTROL_RESET (1UL << 2)
#define GSW_PCM_CONTROL_MASK (GSW_PCM_CONTROL_START | GSW_PCM_CONTROL_STOP | GSW_PCM_CONTROL_RESET)

#define GSW_PCM_IRQ_PERIOD   (1UL << 0)
#define GSW_PCM_IRQ_UNDERRUN (1UL << 1)
#define GSW_PCM_IRQ_INVALID  (1UL << 2)
#define GSW_PCM_IRQ_MASK (GSW_PCM_IRQ_PERIOD | GSW_PCM_IRQ_UNDERRUN | GSW_PCM_IRQ_INVALID)

#define GSW_PCM_FORMAT_CHANNELS_MASK 0x000000FFUL
#define GSW_PCM_FORMAT_BITS_SHIFT    8
#define GSW_PCM_FORMAT_BITS_MASK     0x0000FF00UL
#define GSW_PCM_FORMAT_MASK (GSW_PCM_FORMAT_CHANNELS_MASK | GSW_PCM_FORMAT_BITS_MASK)
#define GSW_PCM_FORMAT(channels, bits) \
    ((gsw_u32)(channels) | ((gsw_u32)(bits) << GSW_PCM_FORMAT_BITS_SHIFT))

#define GSW_PCM_MASTER_GAIN_SILENT 0UL
#define GSW_PCM_MASTER_GAIN_UNITY  65536UL

#endif
