# SPDX-License-Identifier: GPL-3.0-only

[CmdletBinding()]
param()

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'vkd3d-shader-source-root.ps1')
. (Join-Path $PSScriptRoot 'vkd3d-shader-generated-license.ps1')

$utf8 = [Text.UTF8Encoding]::new($false)
$passed = 0
$failed = 0
$inputsByOutput = @{
    'libs/vkd3d-shader/hlsl.yy.c' = @('libs/vkd3d-shader/hlsl.l')
    'libs/vkd3d-shader/hlsl.tab.c' = @('libs/vkd3d-shader/hlsl.y')
    'libs/vkd3d-shader/hlsl.tab.h' = @('libs/vkd3d-shader/hlsl.y')
    'libs/vkd3d-shader/preproc.yy.c' = @('libs/vkd3d-shader/preproc.l')
    'libs/vkd3d-shader/preproc.tab.c' = @('libs/vkd3d-shader/preproc.y')
    'libs/vkd3d-shader/preproc.tab.h' = @('libs/vkd3d-shader/preproc.y')
    'include/vkd3d_d3dcommon.h' = @(
        'include/vkd3d_d3dcommon.idl',
        'include/vkd3d_unknown.idl'
    )
    'include/vkd3d_d3dx9shader.h' = @(
        'include/vkd3d_d3dx9shader.idl',
        'include/vkd3d_d3d9types.h'
    )
    'include/private/spirv_grammar.h' = @(
        'libs/vkd3d-shader/make_spirv',
        'include/private/spirv.core.grammar.json'
    )
    'include/config.h' = @('configure.ac')
    'include/private/vkd3d_version.h' = @('Makefile.am')
}

function Invoke-LicenseCase {
    param([string]$Name, [scriptblock]$Body, [bool]$ShouldPass)

    try {
        & $Body
        if (-not $ShouldPass) { throw 'Expected rejection.' }
        $script:passed++
    }
    catch {
        if ($ShouldPass) {
            $script:failed++
            Write-Host "FAIL: $Name - $($_.Exception.Message)"
        }
        else { $script:passed++ }
    }
}

function Get-TestGeneratedLicense {
    param([string]$RelativePath, [byte[]]$Bytes)

    return Get-Vkd3dShaderGeneratedLicense -RelativePath $RelativePath `
        -Bytes $Bytes -InputRelativePaths @($inputsByOutput[$RelativePath])
}

$bison = $utf8.GetBytes(@'
GNU General Public License as published by
either version 3 of the License, or
As a special exception, you may create a larger work
'@.Replace("`r`n", "`n") + "`n")
$flex = $utf8.GetBytes(
    "A lexical scanner generated by flex`nterms of the GNU Lesser General Public`n"
)

foreach ($path in @(
    'libs/vkd3d-shader/hlsl.tab.c',
    'libs/vkd3d-shader/hlsl.tab.h',
    'libs/vkd3d-shader/preproc.tab.c',
    'libs/vkd3d-shader/preproc.tab.h'
)) {
    Invoke-LicenseCase "Bison disposition $path" {
        $result = Get-TestGeneratedLicense $path $bison
        if ($result.license_expression -cne
            'LGPL-2.1-or-later AND (GPL-3.0-or-later WITH Bison-exception-2.2)') {
            throw 'Bison expression changed.'
        }
        if ($result.provenance -cne
            'bison-3.8.2-skeleton-exception-and-exact-lgpl-grammar-input') {
            throw 'Bison provenance changed.'
        }
    } $true
}

Invoke-LicenseCase 'Bison header uses exact grammar provenance' {
    $header = $utf8.GetBytes(
        "GNU General Public License as published by`n" +
        "either version 3 of the License, or`n" +
        "As a special exception, you may create a larger work`n"
    )
    [void](Get-TestGeneratedLicense `
        'libs/vkd3d-shader/hlsl.tab.h' $header)
} $true

Invoke-LicenseCase 'Bison GPL version drift rejected' {
    $wrongVersion = $utf8.GetBytes(
        "GNU General Public License as published by`n" +
        "either version 2 of the License, or`n" +
        "As a special exception, you may create a larger work`n"
    )
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.tab.h' `
        -Bytes $wrongVersion `
        -InputRelativePaths @('libs/vkd3d-shader/hlsl.y'))
} $false

Invoke-LicenseCase 'Bison C rejects wrong grammar binding' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.tab.c' `
        -Bytes $bison `
        -InputRelativePaths @('libs/vkd3d-shader/preproc.y'))
} $false

Invoke-LicenseCase 'Bison C rejects case-drifted grammar binding' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.tab.c' `
        -Bytes $bison `
        -InputRelativePaths @('libs/vkd3d-shader/HLSL.y'))
} $false

Invoke-LicenseCase 'Bison C rejects missing grammar binding' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.tab.c' `
        -Bytes $bison `
        -InputRelativePaths @())
} $false

foreach ($path in @(
    'libs/vkd3d-shader/hlsl.yy.c',
    'libs/vkd3d-shader/preproc.yy.c'
)) {
    Invoke-LicenseCase "Flex disposition $path" {
        $result = Get-TestGeneratedLicense $path $flex
        if ($result.license_expression -cne 'LGPL-2.1-or-later') {
            throw 'Flex expression changed.'
        }
    } $true
}

Invoke-LicenseCase 'WIDL exact input/version disposition' {
    $bytes = $utf8.GetBytes(
        'Autogenerated by WIDL 11.0-rc1 from include/vkd3d_d3dcommon.idl' + "`n"
    )
    [void](Get-TestGeneratedLicense `
        'include/vkd3d_d3dcommon.h' $bytes)
} $true

Invoke-LicenseCase 'WIDL exact secondary input disposition' {
    $bytes = $utf8.GetBytes(
        'Autogenerated by WIDL 11.0-rc1 from include/vkd3d_d3dx9shader.idl' + "`n"
    )
    [void](Get-TestGeneratedLicense `
        'include/vkd3d_d3dx9shader.h' $bytes)
} $true

Invoke-LicenseCase 'WIDL wrong input rejected' {
    $bytes = $utf8.GetBytes(
        'Autogenerated by WIDL 11.0-rc1 from include/other.idl' + "`n"
    )
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'include/vkd3d_d3dcommon.h' `
        -Bytes $bytes `
        -InputRelativePaths @($inputsByOutput['include/vkd3d_d3dcommon.h']))
} $false

Invoke-LicenseCase 'WIDL reordered inputs rejected' {
    $bytes = $utf8.GetBytes(
        'Autogenerated by WIDL 11.0-rc1 from include/vkd3d_d3dcommon.idl' + "`n"
    )
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'include/vkd3d_d3dcommon.h' `
        -Bytes $bytes `
        -InputRelativePaths @(
            'include/vkd3d_unknown.idl',
            'include/vkd3d_d3dcommon.idl'
        ))
} $false

Invoke-LicenseCase 'SPIR-V MIT disposition' {
    $bytes = $utf8.GetBytes(
        "The original source is covered by the following license:`n" +
        "Permission is hereby granted, free of charge`n"
    )
    [void](Get-TestGeneratedLicense `
        'include/private/spirv_grammar.h' $bytes)
} $true

Invoke-LicenseCase 'exact config disposition' {
    [void](Get-TestGeneratedLicense `
        'include/config.h' (Get-Vkd3dShaderExpectedConfigBytes))
} $true

Invoke-LicenseCase 'config drift rejected' {
    [void](Get-TestGeneratedLicense `
        'include/config.h' $utf8.GetBytes("#define DRIFT 1`n"))
} $false

Invoke-LicenseCase 'exact version disposition' {
    [void](Get-TestGeneratedLicense `
        'include/private/vkd3d_version.h' `
        (Get-Vkd3dShaderExpectedVersionBytes))
} $true

Invoke-LicenseCase 'short version rejected' {
    [void](Get-TestGeneratedLicense `
        'include/private/vkd3d_version.h' `
        $utf8.GetBytes('#define VKD3D_VCS_ID " (git 1b0924d)"' + "`n"))
} $false

Invoke-LicenseCase 'unknown output rejected' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'include/unknown.h' -Bytes $flex `
        -InputRelativePaths @('include/unknown.in'))
} $false

Invoke-LicenseCase 'CRLF output rejected' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.yy.c' `
        -Bytes $utf8.GetBytes("A lexical scanner generated by flex`r`n") `
        -InputRelativePaths @('libs/vkd3d-shader/hlsl.l'))
} $false

Invoke-LicenseCase 'UTF-8 BOM output rejected' {
    [byte[]]$bom = 0xef, 0xbb, 0xbf
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.yy.c' `
        -Bytes ($bom + $flex) `
        -InputRelativePaths @('libs/vkd3d-shader/hlsl.l'))
} $false

foreach ($badPath in @(
    'C:/private/hlsl.yy.c',
    'C:private/hlsl.yy.c',
    'libs/./hlsl.yy.c',
    'libs//hlsl.yy.c',
    'libs\hlsl.yy.c',
    ('libs/' + ('x' * 1024))
)) {
    Invoke-LicenseCase "unsafe output path rejected: $badPath" {
        [void](Get-Vkd3dShaderGeneratedLicense `
            -RelativePath $badPath -Bytes $flex `
            -InputRelativePaths @('libs/vkd3d-shader/hlsl.l'))
    } $false
}

Invoke-LicenseCase 'unsafe generated input path rejected' {
    [void](Get-Vkd3dShaderGeneratedLicense `
        -RelativePath 'libs/vkd3d-shader/hlsl.yy.c' `
        -Bytes $flex -InputRelativePaths @('C:/private/hlsl.l'))
} $false

Write-Host "vkd3d-shader generated-license tests: $passed passed, $failed failed"
if ($failed -ne 0) { exit 1 }
